"""Courses Updated

Revision ID: 14e39cd8d178
Revises: 1dcfa769c3e1
Create Date: 2023-04-20 10:25:01.135171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e39cd8d178'
down_revision = '1dcfa769c3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elective_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('elective_type')

    # ### end Alembic commands ###
