"""ScholarshipDB updated & CoursesOfferes added!

Revision ID: 1dcfa769c3e1
Revises: b2700d350e48
Create Date: 2023-04-20 10:23:15.634018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcfa769c3e1'
down_revision = 'b2700d350e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_offered',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('sem', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('elective_type', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.teacher_id'], ),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('icard',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sign', sa.LargeBinary(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('scholarship_db',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('otherAppliedScholarships', sa.String(), nullable=True),
    sa.Column('otherAppliedScholarshipsAmount', sa.Integer(), nullable=True),
    sa.Column('otherAppliedScholarshipsOrganization', sa.String(), nullable=True),
    sa.Column('otherAppliedScholarshipsStartDate', sa.Date(), nullable=True),
    sa.Column('otherAppliedScholarshipsEndDate', sa.Date(), nullable=True),
    sa.Column('ongoingScholarships', sa.String(), nullable=True),
    sa.Column('ongoingScholarshipsAmount', sa.Integer(), nullable=True),
    sa.Column('ongoingScholarshipsOrganization', sa.String(), nullable=True),
    sa.Column('ongoingScholarshipsStartDate', sa.Date(), nullable=True),
    sa.Column('ongoingScholarshipsEndDate', sa.Date(), nullable=True),
    sa.Column('bankName', sa.String(), nullable=True),
    sa.Column('bankAccountNumber', sa.String(), nullable=True),
    sa.Column('bankIFSC', sa.String(), nullable=True),
    sa.Column('bankBranch', sa.String(), nullable=True),
    sa.Column('fatherOccupation', sa.String(), nullable=True),
    sa.Column('fatherIncome', sa.Integer(), nullable=True),
    sa.Column('motherOccupation', sa.String(), nullable=True),
    sa.Column('motherIncome', sa.Integer(), nullable=True),
    sa.Column('guardianOccupation', sa.String(), nullable=True),
    sa.Column('guardianIncome', sa.Integer(), nullable=True),
    sa.Column('other', sa.LargeBinary(), nullable=True),
    sa.Column('bpb', sa.LargeBinary(), nullable=True),
    sa.Column('bs', sa.LargeBinary(), nullable=True),
    sa.Column('form16', sa.LargeBinary(), nullable=True),
    sa.Column('formsch01c', sa.LargeBinary(), nullable=True),
    sa.Column('formsch01b', sa.LargeBinary(), nullable=True),
    sa.Column('formsch01a', sa.LargeBinary(), nullable=True),
    sa.Column('formic', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scholarship_db')
    op.drop_table('icard')
    op.drop_table('courses_offered')
    # ### end Alembic commands ###
