"""tables temp v

Revision ID: 2c203d99df15
Revises: 9a3905fdad30
Create Date: 2023-03-16 15:44:17.376419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c203d99df15'
down_revision = '9a3905fdad30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('class_id', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('index', sa.INTEGER(), nullable=False),
    sa.Column('sem', sa.INTEGER(), nullable=True),
    sa.Column('elective_type', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    # ### end Alembic commands ###
