"""empty message

Revision ID: 9a3905fdad30
Revises: 2af9a70b5dc8
Create Date: 2023-03-16 14:37:53.187071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3905fdad30'
down_revision = '2af9a70b5dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('elective_type', sa.String(), nullable=True))
        batch_op.alter_column('class_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(), nullable=True))

    with op.batch_alter_table('exam_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exam_type', sa.String(), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('batch',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('exam_result', schema=None) as batch_op:
        batch_op.drop_column('exam_type')
        batch_op.drop_column('exam_name')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('course_name')
        batch_op.drop_column('credits')

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.alter_column('class_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('elective_type')
        batch_op.drop_column('sem')
        batch_op.drop_column('index')

    # ### end Alembic commands ###
